version: '3'

services:
  accounts:
    build: .
    container_name: fiber
    ports:
      - "8000:8000"
    networks:
      - fiber
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fiber_layout
    networks:
      - fiber

networks:
  fiber:
    driver: bridge
