
server:
  listen: "localhost:8000"
  uploadSwitch: true
  wildcardSwitch: false
  wildcardSuffix: ".example.com"
  sessionName: "fiber-layout"
  storeKeyPairs: "fiber-layout"

log:
  level: "info"
  dir: "./data/log"
  fullStackSwitch: false # log full panic stack information

database:
  dbType: "postgres"
  host: "postgres"
  port: 5432
  dbName: "fiber_layout"
  username: "admin"
  password: "admin"
